skins.2=2
name.2=iregex:(Inferno Zombie|.* g1)

skins.3=3
name.3=iregex:(Torrential Zombie|.* g1)

skins.4=4
name.4=iregex:(Charged Zombie|.* g1)

skins.5=5
name.5=iregex:(Terra Zombie|.* g1)

skins.6=6
name.6=iregex:(Metalic Zombie|.* g1)

skins.7=7
name.7=iregex:(Tempest Zombie|.* g1)

skins.8=8
name.8=iregex:(KFC Chicken|.* g1)

skins.9=9
name.9=iregex:(Suit|.* g1)